Repository kubeflow/frontend, pull requests merged in 2020-01, with the labels that each got.

#8 Fixes from bug bash and integration with kubeflow/metadata
  build/lib/common/Utils.js
  build/lib/common/Utils.js.map
  build/lib/generated/ml_metadata/proto/metadata_store_pb.js
  build/lib/generated/ml_metadata/proto/metadata_store_pb.js.map
  build/lib/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.js
  build/lib/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.js.map
  build/lib/generated/ml_metadata/proto/metadata_store_service_pb.js
  build/lib/generated/ml_metadata/proto/metadata_store_service_pb.js.map
  build/lib/index.js
  build/lib/index.js.map
  build/lib/mlmd/Css.js
  build/lib/mlmd/Css.js.map
  build/lib/mlmd/LineageActionBar.js
  build/lib/mlmd/LineageActionBar.js.map
  build/lib/mlmd/LineageApi.js
  build/lib/mlmd/LineageApi.js.map
  build/lib/mlmd/LineageCard.js
  build/lib/mlmd/LineageCard.js.map
  build/lib/mlmd/LineageCardRow.js
  build/lib/mlmd/LineageView.js
  build/lib/mlmd/LineageView.js.map
  build/lib/mlmd/Utils.js
  build/lib/mlmd/Utils.js.map
  build/lib/mlmd/pages/ArtifactDetails.js
  build/lib/mlmd/pages/ArtifactDetails.js.map
  build/lib/mlmd/pages/ArtifactList.js
  build/lib/mlmd/pages/ArtifactList.js.map
  build/lib/mlmd/pages/ExecutionDetails.js
  build/lib/mlmd/pages/ExecutionDetails.js.map
  build/lib/mlmd/pages/ExecutionList.js
  build/lib/mlmd/pages/ExecutionList.js.map
  package-lock.json
  package.json
  src/common/Utils.test.ts
  src/common/Utils.ts
  src/index.ts
  src/mlmd/Css.tsx
  src/mlmd/LineageActionBar.tsx
  src/mlmd/LineageApi.ts
  src/mlmd/LineageCard.tsx
  src/mlmd/LineageCardRow.tsx
  src/mlmd/LineageView.tsx
  src/mlmd/Utils.test.ts
  src/mlmd/Utils.tsx
Labels: approved, area/front-end, area/metadata, kind/feature, lgtm, size/XXL

#21 [BugBash][MLMD] Execution/Artifact Name clipping and formatting
  build/lib/mlmd/LineageCard.js
  build/lib/mlmd/LineageCard.js.map
  src/mlmd/LineageActionBar.tsx
  src/mlmd/LineageCard.tsx
Labels: approved, area/front-end, area/metadata, lgtm, priority/p1, size/S

#20 [MLMD] [Docs] Added docs for developers with commands and instructions
  README.md
Labels: approved, area/front-end, area/metadata, lgtm, priority/p1, size/M

#22 [MLMD][BugBash] Make card titles link to resource details pages
  build/lib/mlmd/LineageCard.js
  build/lib/mlmd/LineageCard.js.map
  build/lib/mlmd/LineageCardRow.js
  build/lib/mlmd/LineageCardRow.js.map
  build/lib/mlmd/LineageTypes.js.map
  build/lib/mlmd/LineageView.js
  build/lib/mlmd/LineageView.js.map
  package-lock.json
  package.json
  src/mlmd/LineageCard.tsx
  src/mlmd/LineageCardRow.tsx
  src/mlmd/LineageTypes.ts
  src/mlmd/LineageView.tsx
  src/mlmd/__snapshots__/LineageActionBar.test.tsx.snap
Labels: approved, lgtm, size/L

#23 [MLMD] Backport MLMD Utils and APIs added to Pipelines since Jan 8
  build/lib/index.js
  build/lib/index.js.map
  build/lib/mlmd/Api.js
  build/lib/mlmd/Api.js.map
  build/lib/mlmd/LineageApi.js
  build/lib/mlmd/LineageApi.js.map
  build/lib/mlmd/Utils.js
  build/lib/mlmd/Utils.js.map
  src/index.ts
  src/mlmd/Api.ts
  src/mlmd/LineageApi.ts
  src/mlmd/Utils.tsx
Labels: approved, area/front-end, lgtm, size/L

#26 [BugBash] Added `Run-Id` as the primary subtext
  build/lib/mlmd/Api.js
  build/lib/mlmd/Api.js.map
  build/lib/mlmd/LineageActionBar.js
  build/lib/mlmd/LineageActionBar.js.map
  build/lib/mlmd/Utils.js
  build/lib/mlmd/Utils.js.map
  src/mlmd/Api.ts
  src/mlmd/LineageActionBar.tsx
  src/mlmd/Utils.tsx
Labels: approved, area/front-end, area/metadata, lgtm, priority/p0, size/L
