Repository kubeflow/frontend, pull requests merged in 2020-02, with the labels that each got.

#29 Update MLMD protos to 0.21.0
  proto/ml_metadata/proto/metadata_store.proto
  proto/ml_metadata/proto/metadata_store_service.proto
  src/mlmd/generated/ml_metadata/proto/metadata_store_pb.d.ts
  src/mlmd/generated/ml_metadata/proto/metadata_store_pb.js
  src/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.d.ts
  src/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.js
  src/mlmd/generated/ml_metadata/proto/metadata_store_service_pb.d.ts
  src/mlmd/generated/ml_metadata/proto/metadata_store_service_pb.js
Labels: approved, lgtm, size/XXL

#30 Export more MLMD types
  src/index.ts
  src/mlmd/Api.ts
Labels: approved, lgtm, size/S

#32 Fix package name
  package.json
Labels: approved, lgtm, size/XS

#31 [BugBash][MLMD][Hotfix] Fixed `getResourcePropertyViaFallBack` to resolve props from all repos
  build/lib/mlmd/Api.js
  build/lib/mlmd/Api.js.map
  build/lib/mlmd/Utils.js
  build/lib/mlmd/Utils.js.map
  src/mlmd/Api.ts
  src/mlmd/Utils.tsx
Labels: approved, area/front-end, area/metadata, kind/hotfix, lgtm, priority/p0, size/M

#35 Rebuild lib
  build/lib/index.js
  build/lib/index.js.map
  build/lib/mlmd/Api.js
  build/lib/mlmd/Api.js.map
  build/lib/mlmd/generated/ml_metadata/proto/metadata_store_pb.js
  build/lib/mlmd/generated/ml_metadata/proto/metadata_store_pb.js.map
  build/lib/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.js
  build/lib/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.js.map
  build/lib/mlmd/generated/ml_metadata/proto/metadata_store_service_pb.js
  build/lib/mlmd/generated/ml_metadata/proto/metadata_store_service_pb.js.map
Labels: approved, lgtm, size/XXL

#34 Clean up dependencies, move to dev/peer correspondingly
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#27 [BugBash][MLMD] Responsive Design MLMD, pivoted logic on `columnPadding`
  build/lib/mlmd/EdgeCanvas.js
  build/lib/mlmd/EdgeCanvas.js.map
  build/lib/mlmd/LineageCard.js
  build/lib/mlmd/LineageCard.js.map
  build/lib/mlmd/LineageCardColumn.js
  build/lib/mlmd/LineageCardColumn.js.map
  build/lib/mlmd/LineageView.js
  build/lib/mlmd/LineageView.js.map
  build/lib/mlmd/Utils.js
  build/lib/mlmd/Utils.js.map
  src/mlmd/EdgeCanvas.tsx
  src/mlmd/LineageCard.tsx
  src/mlmd/LineageCardColumn.tsx
  src/mlmd/LineageView.tsx
  src/mlmd/Utils.tsx
Labels: approved, area/front-end, area/metadata, lgtm, priority/p0, size/XXL

#28 [MLMD Lineage] Improve target card selection
  build/lib/mlmd/LineageCard.js
  build/lib/mlmd/LineageCard.js.map
  build/lib/mlmd/LineageCardRow.js
  build/lib/mlmd/LineageCardRow.js.map
  src/mlmd/LineageCard.tsx
  src/mlmd/LineageCardRow.tsx
Labels: approved, area/front-end, lgtm, size/L

#37 [MLMD Lineage] Remove pointer cursor from lineage edges
  build/lib/mlmd/LineageCardRow.js
  build/lib/mlmd/LineageCardRow.js.map
  src/mlmd/LineageCardRow.tsx
Labels: approved, lgtm, size/M

#40 [BugBash][MLMD] Exec Cards updated to look drastically different
  build/lib/mlmd/LineageCard.js
  build/lib/mlmd/LineageCard.js.map
  build/lib/mlmd/LineageView.js
  src/mlmd/LineageCard.tsx
  src/mlmd/LineageView.tsx
Labels: approved, area/front-end, area/metadata, lgtm, priority/p0, size/M

#41 Export `getResourcePropertyViaFallBack()` to use in KFP
  build/lib/index.js
  build/lib/index.js.map
  src/index.ts
Labels: approved, lgtm, size/S

#42 Fix missing ActionBar breadcrumbs
  build/lib/mlmd/LineageActionBar.js
  build/lib/mlmd/LineageActionBar.js.map
  build/lib/mlmd/Utils.js
  build/lib/mlmd/Utils.js.map
  src/mlmd/LineageActionBar.tsx
  src/mlmd/Utils.tsx
Labels: approved, lgtm, size/M

#44 [MLMD] Add support for many-to-many <EdgeCanvas>
  build/lib/index.js.map
  build/lib/mlmd/ControlledEdgeCanvas.js
  build/lib/mlmd/ControlledEdgeCanvas.js.map
  build/lib/mlmd/EdgeCanvas.js
  build/lib/mlmd/EdgeCanvas.js.map
  build/lib/mlmd/EdgeLine.js
  build/lib/mlmd/EdgeLine.js.map
  build/lib/mlmd/LineageActionBar.js
  build/lib/mlmd/LineageActionBar.js.map
  build/lib/mlmd/LineageCard.js
  build/lib/mlmd/LineageCard.js.map
  build/lib/mlmd/LineageCardColumn.js
  build/lib/mlmd/LineageCardColumn.js.map
  build/lib/mlmd/LineageCss.js
  build/lib/mlmd/LineageCss.js.map
  build/lib/mlmd/LineageView.js
  build/lib/mlmd/LineageView.js.map
  package-lock.json
  package.json
  src/index.ts
  src/mlmd/ControlledEdgeCanvas.tsx
  src/mlmd/EdgeCanvas.tsx
  src/mlmd/EdgeLine.tsx
  src/mlmd/LineageActionBar.tsx
  src/mlmd/LineageCard.tsx
  src/mlmd/LineageCardColumn.tsx
  src/mlmd/LineageCss.ts
  src/mlmd/LineageView.tsx
Labels: approved, area/front-end, lgtm, priority/p0, size/XXL

#45 [MLMD][BugBash] Support many-to-many grouped executions
  build/lib/mlmd/LineageCardColumn.js
  build/lib/mlmd/LineageCardColumn.js.map
  build/lib/mlmd/LineageView.js
  build/lib/mlmd/LineageView.js.map
  src/mlmd/LineageCardColumn.tsx
  src/mlmd/LineageView.tsx
Labels: approved, area/front-end, lgtm, priority/p0, size/L
